from scoreanim.core.project.commands import (AddCondenseGroup, AddStaffGroup,
                                             AddSwingRegion,
                                             AddTempoEvent, AddTempoOverlay,
                                             AlignBeat,
                                             ApplyScoreSetup,
                                             ApplyTaps, Command, CommandError,
                                             EditCondenseGroup,
                                             EditStaffGroup, EditStageText,
                                             ImportTempoSetup, MoveTempoEvent,
                                             RemoveCondenseGroup,
                                             RemoveStaffGroup,
                                             RemoveSwingRegion,
                                             RemoveTapSession,
                                             RemoveTempoEvent,
                                             RemoveTempoOverlay,
                                             ResetEffectSettings,
                                             SetDefaultEffect,
                                             SetEffectParam,
                                             SetElementStyle,
                                             SetElementsHidden,
                                             SetFloorOpacity, SetGlobalSwing,
                                             SetHideEmptyStaves,
                                             SetHideFirstSystem,
                                             SetOffset, SetPageBreak,
                                             SetPartColor,
                                             SetLayoutOverride,
                                             SetPartEffect, SetPartText,
                                             SetPresentationMode,
                                             SetRevealMode,
                                             SetSwingRegion, SetSystemBreak,
                                             UndoStack)
from scoreanim.core.project.document import (DEFAULT_BPM,
                                             HIDE_EMPTY_STAVES_DEFAULT,
                                             CondenseGroup,
                                             FileRef, LayoutOverride,
                                             PageBreak, PartTextOverride,
                                             ProjectDoc,
                                             StaffGroup, StyleRules,
                                             SystemBreak, TimingConfig)
from scoreanim.core.project.serialize import (PROJECT_VERSION, SUFFIX,
                                              check_ref, from_dict,
                                              load_project, save_project,
                                              sha256_of, to_dict)
from scoreanim.core.project.stage_config import (OVERLAY_PREFIX,
                                                 PresentationMode,
                                                 StageConfig,
                                                 StageTextElement,
                                                 default_stage_config,
                                                 fit_texts, is_header_text,
                                                 page_content_top)

__all__ = [
    "AddCondenseGroup", "AddStaffGroup", "AddSwingRegion", "AddTempoEvent",
    "AddTempoOverlay", "AlignBeat",
    "ApplyScoreSetup", "ApplyTaps",
    "Command", "CommandError", "CondenseGroup", "DEFAULT_BPM",
    "EditCondenseGroup", "EditStaffGroup",
    "EditStageText", "FileRef", "HIDE_EMPTY_STAVES_DEFAULT",
    "ImportTempoSetup", "LayoutOverride", "MoveTempoEvent", "OVERLAY_PREFIX",
    "PROJECT_VERSION", "PartTextOverride", "PresentationMode", "ProjectDoc",
    "RemoveCondenseGroup", "RemoveStaffGroup", "RemoveSwingRegion",
    "RemoveTapSession",
    "RemoveTempoEvent", "RemoveTempoOverlay", "ResetEffectSettings",
    "SUFFIX", "SetDefaultEffect", "SetEffectParam",
    "SetElementStyle", "SetFloorOpacity", "SetGlobalSwing",
    "SetHideEmptyStaves", "SetHideFirstSystem",
    "SetElementsHidden",
    "SetLayoutOverride", "SetOffset", "SetPageBreak",
    "SetPartColor", "SetPartEffect",
    "SetPartText",
    "SetPresentationMode",
    "SetRevealMode", "SetSwingRegion", "SetSystemBreak", "StaffGroup",
    "StageConfig",
    "PageBreak",
    "StageTextElement", "StyleRules", "SystemBreak", "TimingConfig",
    "UndoStack",
    "check_ref", "default_stage_config", "fit_texts", "from_dict",
    "is_header_text", "load_project",
    "page_content_top", "save_project", "sha256_of", "to_dict",
]
